version: '3.0'

expectations:
  population_size: 50000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_study_population_COD:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_COD
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/input_COD.csv
        
  data_manage:
    run: r:latest analysis/data_manage.R
    needs: [generate_study_population,generate_study_population_COD]
    outputs:
      highly_sensitive:
        cohort: output/cohort_long.feather

  data_manage_postdisch_week:
    run: r:latest analysis/data_manage_postdisch_weeks.R
    needs: [generate_study_population,data_manage]
    outputs:
      highly_sensitive:
        cohort_splits: output/cohort_postdisch_week_splits.feather

  flowchart:      
    run: r:latest analysis/FlowChart.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        flowchart_data: output/flowchart.RData
        flowchart_fig: output/Flowchart.pdf
        
  table_demo:      
    run: r:latest analysis/Table_demo.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_demo: output/table_demo.csv

  table_postopcovid_crude:      
    run: r:latest analysis/Table_postopcovid_crude.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_crude: output/postopcovid_crude.RData
        table_crude_csv: output/postopcovid_crude.csv
        
  table_postopcovid_crude_sub:      
    run: r:latest analysis/Table_postopcovid_crude_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_crude: output/postopcovid_crude_sub.RData
        table_crude_csv: output/postopcovid_crude_sub.csv
       
  table_postopcovid_adjusted:      
    run: r:latest analysis/Table_postopcovid_adjusted.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_adjusted: output/postopcovid_adjusted.RData
        table_adjusted_csv: output/postopcovid_adjusted.csv
        model_adjusted: output/postopcovidmodel.csv
        model_adjusted_waves: output/postopcovidmodelwaves.csv
        plot_adjusted_waves: output/adjusted_waves_plot.png
       
  table_postopcovid_adjusted_per_op:      
    run: r:latest analysis/Table_postopcovid_adjusted_per_op.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_adjusted: output/postopcovid_adjusted_per_op.RData
        table_adjusted_csv: output/postopcovid_adjusted_per_op*.csv

  table_postopcovid_adjusted_bootstrap:      
    run: r:latest analysis/Table_postopcovid_adjusted_bootstrap.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        samples_adjusted: output/postopcovid_adjusted_bootstrappedIQR.RData
        summary_boot_adjusted_csv: output/postopcovid_adjusted_bootstrappedIQR.csv


  table_postopcovid_adjusted_bootstrap_sub:      
    run: r:latest analysis/Table_postopcovid_adjusted_bootstrap_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        samples_adjusted: output/postopcovid_adjusted_bootstrappedIQR_sub.RData
        summary_boot_adjusted_csv: output/postopcovid_adjusted_bootstrappedIQR_sub.csv

  table_postopcovid_adjusted_sub:      
    run: r:latest analysis/Table_postopcovid_adjusted_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_adjusted_sub: output/postopcovid_adjusted_sub.RData
        table_adjusted_sub_csv: output/postopcovid_adjusted_sub.csv
        model_adjusted_sub: output/postopcovidmodelsub.csv
        model_adjusted_waves_sub: output/postopcovidmodelwavessub.csv
        plot_adjusted_waves_sub: output/adjusted_waves_sub_plot.png

  table_postopcovid_tv:      
    run: r:latest analysis/Table_postopcovid_tv.R
    needs: [generate_study_population, data_manage,data_manage_postdisch_week]
    outputs:
      moderately_sensitive:
        table_tv: output/postopcovid_tv.RData
        table_tv_csv: output/postopcovid_tv.csv
        model_VTE_tv: output/postopVTEmodelsplit.csv
        table_tv_VTE_csv: output/postopcovid_VTE_tv.csv      
        model_COVID_tv: output/postopcovidmodelsplit.csv

  table_postopcovid_tv_daily:      
    run: r:latest analysis/Table_postopcovid_tv_continuous.R
    needs: [generate_study_population, data_manage,data_manage_postdisch_week]
    outputs:
      moderately_sensitive:
        table_tv_daily: output/postopcovid_tv_daily.RData
        table_tv_csv_daily: output/daily_postopcovid_tv.csv
        plot_tv_daily: output/dailyCovidRisk.pdf
        table_tv_VTE_csv_daily: output/daily_postopcovid_VTE_tv.csv    
        plot_tv_VTE_daily: output/dailyVTERisk.pdf

  table_postopcovid_tv_sub:      
    run: r:latest analysis/Table_postopcovid_tv_sub.R
    needs: [generate_study_population, data_manage,data_manage_postdisch_week]
    outputs:
      moderately_sensitive:
        table_tv_sub: output/postopcovid_tv_sub.RData
        table_tv_sub_csv: output/postopcovid_tv_sub.csv
        model_VTE_tv_sub: output/postopVTEmodelsplitsub.csv
        table_VTE_tv_sub_csv: output/postopcovid_VTE_tv_sub.csv
        model_COVID_tv_sub: output/postopcovidmodelsplitsub.csv
        
  table_postopcovid_tv_daily_sub:      
    run: r:latest analysis/Table_postopcovid_tv_continuous_sub.R
    needs: [generate_study_population, data_manage,data_manage_postdisch_week]
    outputs:
      moderately_sensitive:
        table_tv_daily_sub: output/postopcovid_tv_daily_sub.RData
        table_tv_csv_daily_sub: output/daily_postopcovid_tv_sub.csv
        plot_tv__daily_sub: output/dailyCovidRiskSub.pdf
        table_tv_VTE_csv_daily_sub: output/daily_postopcovid_VTE_tv_sub.csv    
        plot_tv_VTE_daily_sub: output/dailyVTERiskSub.pdf        
        
  table_postopLOS:      
    run: r:latest analysis/Table_postoplos.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_los: output/postoplos.RData
        table_los_csv: output/postoplos.csv
        model_los: output/postopLOSmodel.csv
        
  table_postopLOS_sub:      
    run: r:latest analysis/Table_postoplos_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_los_sub: output/postoplos_sub.RData
        table_los_sub_csv: output/postoplos_sub.csv
        model_los_sub: output/postopLOSmodel_sub.csv
        
  table_postopVTE:      
    run: r:latest analysis/Table_postopVTE.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_VTE: output/postopVTE.RData
        table_VTE_csv: output/postopVTE.csv
        model_VTE: output/postopVTEmodel.csv
        plot_VTE_waves: output/VTE_waves_plot.png
        
  table_postopVTE_sub:      
    run: r:latest analysis/Table_postopVTE_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_VTE_sub: output/postopVTE_sub.RData
        table_VTE_sub_csv: output/postopVTE_sub.csv        
        model_VTE_sub: output/postopVTEmodelsub.csv
        plot_VTE_sub_waves: output/VTE_waves_sub_plot.png
       
  table_postopmortality:      
    run: r:latest analysis/Table_postopmortality.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_mortality: output/postopmortality.RData
        table_mortality_csv: output/postopmortality.csv
        model_mortality: output/postopdiedmodel.csv
        plot_mortality: output/mortality_waves_plot.png
        
  table_postopmortality_sub:      
    run: r:latest analysis/Table_postopmortality_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_mortality_sub: output/postopmortality_sub.RData
        table_mortality_sub_csv: output/postopmortality_sub.csv
        model_mortality_sub: output/postopdiedmodelsub.csv
        plot_mortality_sub: output/mortality_waves_sub_plot.png
  
  table_postopreadmit:      
    run: r:latest analysis/Table_postop_readmit.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_readmit: output/postopreadmit.RData
        table_readmit_csv: output/postopreadmit.csv
        model_readmit: output/postopreadmitmodel.csv
        plot_readmit: output/readmit_waves_plot.png        
        
  table_postopreadmit_sub:      
    run: r:latest analysis/Table_postop_readmit_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_readmit_sub: output/postopreadmit_sub.RData
        table_readmit_sub_csv: output/postopreadmit_sub.csv
        model_readmit_sub: output/postopreadmitmodelsub.csv
        plot_readmit_sub: output/readmit_waves_sub_plot.png

  report:
    run: r:latest -e 'rmarkdown::render("analysis/Report.rmd", output_dir = "/workspace/output/",knit_root_dir = "/workspace",)'    
    needs: [generate_study_population, data_manage, data_manage_postdisch_week,
    flowchart,
    table_demo,
    table_postopcovid_crude,
    table_postopcovid_adjusted,
    table_postopcovid_tv,
    table_postopLOS,
    table_postopVTE,
    table_postopmortality,
    table_postopreadmit,
    table_postopcovid_crude_sub,
    table_postopcovid_adjusted_sub,
    table_postopcovid_tv_sub,
    table_postopLOS_sub,
    table_postopVTE_sub,
    table_postopmortality_sub,
    table_postopreadmit_sub]
    outputs:
      moderately_sensitive:
        results_report: output/Report.html
        


