version: '3.0'

expectations:
  population_size: 100000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv
        
  data_manage:
    run: r:latest analysis/data_manage.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/cohort_long.RData
  
  flowchart:      
    run: r:latest analysis/FlowChart.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        flowchart_data: output/flowchart.RData
        flowchart_fig: output/Flowchart.pdf
        
  table_demo:      
    run: r:latest analysis/Table_demo.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_demo: output/table_demo.RData

  table_postopcovid_crude:      
    run: r:latest analysis/Table_postopcovid_crude.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_crude: output/postopcovid_crude.RData
        
  table_postopcovid_crude_sub:      
    run: r:latest analysis/Table_postopcovid_crude_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_crude: output/postopcovid_crude_sub.RData
        
  table_postopcovid_adjusted:      
    run: r:latest analysis/Table_postopcovid_adjusted.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_adjusted: output/postopcovid_adjusted.RData
        model_adjusted: output/postopcovidmodel.csv
        model_adjusted_waves: output/postopcovidmodelwaves.csv

  table_postopcovid_adjusted_sub:      
    run: r:latest analysis/Table_postopcovid_adjusted_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_adjusted: output/postopcovid_adjusted_sub.RData
        model_adjusted: output/postopcovidmodelsub.csv
        model_adjusted_waves: output/postopcovidmodelwavessub.csv

  table_postopcovid_tv:      
    run: r:latest analysis/Table_postopcovid_tv.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_tv: output/postopcovid_tv.RData
        model_VTE_tv: output/postopVTEmodelsplit.csv
        model_COVID_tv: output/postopcovidmodelsplit.csv

  table_postopcovid_tv_sub:      
    run: r:latest analysis/Table_postopcovid_tv_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_tv: output/postopcovid_tv_sub.RData
        model_VTE_tv: output/postopVTEmodelsplitsub.csv
        model_COVID_tv: output/postopcovidmodelsplitsub.csv
        
  table_postopLOS:      
    run: r:latest analysis/Table_postoplos.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_los: output/postoplos.RData
        model_los: output/postopLOSmodel.csv
        
  table_postopLOS_sub:      
    run: r:latest analysis/Table_postoplos.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_los: output/postoplos_sub.RData
        model_los: output/postopLOSmodel_sub.csv
        
  table_postopVTE:      
    run: r:latest analysis/Table_postopVTE.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_VTE: output/postopVTE.RData
        model_VTE: output/postopVTEmodel.csv
        
  table_postopVTE:      
    run: r:latest analysis/Table_postopVTE_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_VTE: output/postopVTE_sub.RData
        model_VTE: output/postopVTEmodelsub.csv
        
  table_postopmortality:      
    run: r:latest analysis/Table_postopmortality.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_mortality: output/postopmortality.RData
        model_mortality: output/postopdiedmodel.csv
        
  table_postopmortality_sub:      
    run: r:latest analysis/Table_postopmortality_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_mortality: output/postopmortality_sub.RData
        model_mortality: output/postopdiedmodelsub.csv

  analysis_crude:
    run: r:latest analysis/analysis_crude.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        km_figures: output/*_km.png
        crude_tables: output/*_counts.csv

  analysis_adjusted:
    run: r:latest analysis/analysis_adjusted.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        covid_cox_models: output/*_model.csv
        finalfit_tables: output/*_model.html
        
  report:
    run: r:latest -e 'rmarkdown::render("analysis/Results.rmd", output_dir = "/workspace/output/",knit_root_dir = "/workspace",)'    
    needs: [generate_study_population, data_manage, table_demo,table_postopcovid_crude,table_postopcovid_adjusted,table_postopcovid_tv,table_postopLOS,table_postopVTE,flowchart,table_postopmortality,table_postopcovid_crude_sub,table_postopcovid_adjusted_sub,table_postopcovid_tv_sub,table_postopLOS_sub,table_postopVTE_sub,table_postopmortality_sub]
    outputs:
      moderately_sensitive:
        results_report: output/Results.html
        


