version: '3.0'

expectations:
  population_size: 100000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv
        
  data_manage:
    run: r:latest analysis/data_manage.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/cohort_long.RData
  
  flowchart:      
    run: r:latest analysis/FlowChart.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        flowchart_data: output/flowchart.RData
        flowchart_fig: output/Flowchart.pdf
        
  table_demo:      
    run: r:latest analysis/Table_demo.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_demo: output/table_demo.RData

  table_postopcovid_crude:      
    run: r:latest analysis/Table_postopcovid_crude.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_crude: output/postopcovid_crude.RData
        
  table_postopcovid_crude_sub:      
    run: r:latest analysis/Table_postopcovid_crude_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_crude: output/postopcovid_crude_sub.RData
        
  table_postopcovid_adjusted:      
    run: r:latest analysis/Table_postopcovid_adjusted.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_adjusted: output/postopcovid_adjusted.RData
        model_adjusted: output/postopcovidmodel.csv
        model_adjusted_waves: output/postopcovidmodelwaves.csv

  table_postopcovid_adjusted_sub:      
    run: r:latest analysis/Table_postopcovid_adjusted_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_adjusted_sub: output/postopcovid_adjusted_sub.RData
        model_adjusted_sub: output/postopcovidmodelsub.csv
        model_adjusted_waves_sub: output/postopcovidmodelwavessub.csv

  table_postopcovid_tv:      
    run: r:latest analysis/Table_postopcovid_tv.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_tv: output/postopcovid_tv.RData
        model_VTE_tv: output/postopVTEmodelsplit.csv
        model_COVID_tv: output/postopcovidmodelsplit.csv

  table_postopcovid_tv_sub:      
    run: r:latest analysis/Table_postopcovid_tv_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_tv_sub: output/postopcovid_tv_sub.RData
        model_VTE_tv_sub: output/postopVTEmodelsplitsub.csv
        model_COVID_tv_sub: output/postopcovidmodelsplitsub.csv
        
  table_postopLOS:      
    run: r:latest analysis/Table_postoplos.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_los: output/postoplos.RData
        model_los: output/postopLOSmodel.csv
        
  table_postopLOS_sub:      
    run: r:latest analysis/Table_postoplos_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_los_sub: output/postoplos_sub.RData
        model_los_sub: output/postopLOSmodel_sub.csv
        
  table_postopVTE:      
    run: r:latest analysis/Table_postopVTE.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_VTE: output/postopVTE.RData
        model_VTE: output/postopVTEmodel.csv
        
  table_postopVTE_sub:      
    run: r:latest analysis/Table_postopVTE_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_VTE_sub: output/postopVTE_sub.RData
        model_VTE_sub: output/postopVTEmodelsub.csv
        
  table_postopmortality:      
    run: r:latest analysis/Table_postopmortality.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_mortality: output/postopmortality.RData
        model_mortality: output/postopdiedmodel.csv
        
  table_postopmortality_sub:      
    run: r:latest analysis/Table_postopmortality_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_mortality_sub: output/postopmortality_sub.RData
        model_mortality_sub: output/postopdiedmodelsub.csv
  
  table_postopreadmit:      
    run: r:latest analysis/Table_postop_readmit.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_readmit: output/postopreadmit.RData
        model_readmit: output/postopreadmitmodel.csv
        
  table_postopreadmit_sub:      
    run: r:latest analysis/Table_postop_readmit_sub.R
    needs: [generate_study_population, data_manage]
    outputs:
      moderately_sensitive:
        table_readmit_sub: output/postopreadmit_sub.RData
        model_readmit_sub: output/postopreadmitmodelsub.csv

  report:
    run: r:latest -e 'rmarkdown::render("analysis/Results.rmd", output_dir = "/workspace/output/",knit_root_dir = "/workspace",)'    
    needs: [generate_study_population, data_manage, 
    flowchart,
    table_demo,
    table_postopcovid_crude,
    table_postopcovid_adjusted,
    table_postopcovid_tv,
    table_postopLOS,
    table_postopVTE,
    table_postopmortality,
    table_postopreadmit,
    table_postopcovid_crude_sub,
    table_postopcovid_adjusted_sub,
    table_postopcovid_tv_sub,
    table_postopLOS_sub,
    table_postopVTE_sub,
    table_postopmortality_sub,
    table_postopreadmit_sub]
    outputs:
      moderately_sensitive:
        results_report: output/Results.html
        


